####### stand walk run #######
# model_pb: "python_scripts/source/rl_0205_3net_pndone_libtorch_0.pt"
# obs_num: 91
# state_name: "StateMLP"
# joint_config_path: "robot_interface/config/joint_pd_config.json"

####### mlp demo #######
# model_pb: "python_scripts/source/example_obs91.pt"
# obs_num: 91
# joint_config_path: "robot_interface/config/joint_pd_config.json"
# state_name: "StateMlpDemo"

####### ros demo #######
# model_pb: "python_scripts/source/example_obs91.pt"
# obs_num: 91
# joint_config_path: "robot_interface/config/joint_pd_config.json"
# state_name: "StateRosDemo"

####### lcm demo #######
# model_pb: "python_scripts/source/example_obs91.pt"
# obs_num: 91
# joint_config_path: "robot_interface/config/joint_pd_config.json"
# state_name: "StateLcmDemo"

####### pos demo #######
model_pb: "python_scripts/source/example_obs91.pt"
obs_num: 91
joint_config_path: "robot_interface/config/joint_pd_config.json"
state_name: "StatePosDemo"

####### ankle demo #######
# model_pb: "python_scripts/source/example_obs91.pt"
# obs_num: 91
# joint_config_path: "robot_interface/config/joint_pd_config.json"
# state_name: "StateAnkleTestDemo"

StatePosDemo:
  use_linear_actuators: true
  motion:
    # Left leg joints
    hipPitch_Left:       [-0.41, -0.66, -0.02, -0.41]
    hipRoll_Left:        [-0.04, -0.11,  0.003, -0.04]
    hipYaw_Left:         [-0.23, -0.35, -0.015, -0.23]
    kneePitch_Left:      [ 0.81,  0.68,  0.68,  0.81]
    anklePitch_Left:     [-0.47, -0.11, -0.66, -0.47]
    ankleRoll_Left:      [ 0.0,   0.0,   0.0,   0.0 ]
    
    # Right leg joints
    hipPitch_Right:      [-0.41, -0.02, -0.66, -0.41]
    hipRoll_Right:       [ 0.04, -0.003,  0.11,  0.004]
    hipYaw_Right:        [ 0.23,  0.015,  0.35,  0.23]
    kneePitch_Right:     [ 0.81,  0.68,   0.68,  0.81]
    anklePitch_Right:    [-0.47, -0.66,  -0.11, -0.47]
    ankleRoll_Right:     [ 0.0,   0.0,    0.0,   0.0 ]
    
    # Waist joints
    waistRoll:           [ 0.0,   0.0,    0.0,   0.0 ]
    waistPitch:          [ 0.0,   0.0,    0.0,   0.0 ]
    waistYaw:            [ 0.0,   0.0,    0.0,   0.0 ]
    
    # Neck joints
    neckYaw:             [ 0.0,   0.4,   -0.4,   0.0 ]
    neckPitch:           [ 0.0,   0.4,   -0.4,   0.0 ]
    
    # Left arm joints
    shoulderPitch_Left:  [ 0.0,   0.7,   -0.7,   0.0 ]
    shoulderRoll_Left:   [ 0.1,   0.3,    0.3,   0.1 ]
    shoulderYaw_Left:    [ 0.0,   0.0,    0.0,   0.0 ]
    elbow_Left:          [-0.3,  -0.7,   -0.7,  -0.3 ]
    wristYaw_Left:       [ 0.0,   0.4,   -0.4,   0.0 ]
    wristPitch_Left:     [ 0.0,   0.4,   -0.4,   0.0 ]
    wristRoll_Left:      [ 0.0,   0.4,   -0.4,   0.0 ]
    
    # Right arm joints
    shoulderPitch_Right: [ 0.0,  -0.7,    0.7,   0.0 ]
    shoulderRoll_Right:  [-0.1,  -0.3,   -0.3,  -0.1 ]
    shoulderYaw_Right:   [ 0.0,   0.0,    0.0,   0.0 ]
    elbow_Right:         [-0.3,  -0.7,   -0.7,  -0.3 ]
    wristYaw_Right:      [ 0.0,   0.4,   -0.4,   0.0 ]
    wristPitch_Right:    [ 0.0,   0.4,   -0.4,   0.0 ]
    wristRoll_Right:     [ 0.0,   0.4,   -0.4,   0.0 ]

    # leftHand joints
    L_thumb_MCP_joint1:  [ 0.0,   0.5,   0.5,   0.0 ]
    L_thumb_MCP_joint2:  [ 0.0,   0.5,   0.5,   0.0 ]
    L_thumb_PIP_joint:   [ 0.0,   0.5,   0.5,   0.0 ]
    L_thumb_DIP_joint:   [ 0.0,   0.5,   0.5,   0.0 ]
    L_index_MCP_joint:   [ 0.0,   0.5,   0.5,   0.0 ]
    L_index_DIP_joint:   [ 0.0,   0.5,   0.5,   0.0 ]
    L_middle_MCP_joint:  [ 0.0,   0.5,   0.5,   0.0 ]
    L_middle_DIP_joint:  [ 0.0,   0.5,   0.5,   0.0 ]
    L_ring_MCP_joint:    [ 0.0,   0.5,   0.5,   0.0 ]
    L_ring_DIP_joint:    [ 0.0,   0.5,   0.5,   0.0 ]
    L_pinky_MCP_joint:   [ 0.0,   0.5,   0.5,   0.0 ]
    L_pinky_DIP_joint:   [ 0.0,   0.5,   0.5,   0.0 ]
    # rightHand joints
    R_thumb_MCP_joint1:  [ 0.0,   0.5,   0.5,   0.0 ]
    R_thumb_MCP_joint2:  [ 0.0,   0.5,   0.5,   0.0 ]
    R_thumb_PIP_joint:   [ 0.0,   0.5,   0.5,   0.0 ]
    R_thumb_DIP_joint:   [ 0.0,   0.5,   0.5,   0.0 ]
    R_index_MCP_joint:   [ 0.0,   0.5,   0.5,   0.0 ]
    R_index_DIP_joint:   [ 0.0,   0.5,   0.5,   0.0 ]
    R_middle_MCP_joint:  [ 0.0,   0.5,   0.5,   0.0 ]
    R_middle_DIP_joint:  [ 0.0,   0.5,   0.5,   0.0 ]
    R_ring_MCP_joint:    [ 0.0,   0.5,   0.5,   0.0 ]
    R_ring_DIP_joint:    [ 0.0,   0.5,   0.5,   0.0 ]
    R_pinky_MCP_joint:   [ 0.0,   0.5,   0.5,   0.0 ]
    R_pinky_DIP_joint:   [ 0.0,   0.5,   0.5,   0.0 ]

    # hands linear actuator
    l_pinky:               [ 0,   900,   400,   0 ]
    l_ring:                [ 0,   800,   500,   0 ]
    l_middle:              [ 0,   700,   600,   0 ]
    l_index:               [ 0,   600,   700,   0 ]
    l_thumb:               [ 0,   500,   800,   0 ]
    l_thumb_lateral:       [ 500,   900,   900,   500 ]
    r_pinky:               [ 0,   900,   400,   0 ]
    r_ring:                [ 0,   800,   500,   0 ]
    r_middle:              [ 0,   700,   600,   0 ]
    r_index:               [ 0,   600,   700,   0 ]
    r_thumb:               [ 0,   500,   800,   0 ]
    r_thumb_lateral:       [ 500,   900,   900,   500 ]
