"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class pnd_joint_cmd_t(object):

    __slots__ = ["num_joints", "dpos", "dvel", "dtau"]

    __typenames__ = ["int32_t", "double", "double", "double"]

    __dimensions__ = [None, ["num_joints"], ["num_joints"], ["num_joints"]]

    def __init__(self):
        self.num_joints = 0
        """ LCM Type: int32_t """
        self.dpos = []
        """ LCM Type: double[num_joints] """
        self.dvel = []
        """ LCM Type: double[num_joints] """
        self.dtau = []
        """ LCM Type: double[num_joints] """

    def encode(self):
        buf = BytesIO()
        buf.write(pnd_joint_cmd_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.num_joints))
        buf.write(struct.pack('>%dd' % self.num_joints, *self.dpos[:self.num_joints]))
        buf.write(struct.pack('>%dd' % self.num_joints, *self.dvel[:self.num_joints]))
        buf.write(struct.pack('>%dd' % self.num_joints, *self.dtau[:self.num_joints]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != pnd_joint_cmd_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return pnd_joint_cmd_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = pnd_joint_cmd_t()
        self.num_joints = struct.unpack(">i", buf.read(4))[0]
        self.dpos = struct.unpack('>%dd' % self.num_joints, buf.read(self.num_joints * 8))
        self.dvel = struct.unpack('>%dd' % self.num_joints, buf.read(self.num_joints * 8))
        self.dtau = struct.unpack('>%dd' % self.num_joints, buf.read(self.num_joints * 8))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if pnd_joint_cmd_t in parents: return 0
        tmphash = (0x9dccb91599eec47a) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if pnd_joint_cmd_t._packed_fingerprint is None:
            pnd_joint_cmd_t._packed_fingerprint = struct.pack(">Q", pnd_joint_cmd_t._get_hash_recursive([]))
        return pnd_joint_cmd_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", pnd_joint_cmd_t._get_packed_fingerprint())[0]

