"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class pnd_robot_state_t(object):

    __slots__ = ["num_joints", "apos", "avel", "atau"]

    __typenames__ = ["int32_t", "double", "double", "double"]

    __dimensions__ = [None, ["num_joints"], ["num_joints"], ["num_joints"]]

    def __init__(self):
        self.num_joints = 0
        """ LCM Type: int32_t """
        self.apos = []
        """ LCM Type: double[num_joints] """
        self.avel = []
        """ LCM Type: double[num_joints] """
        self.atau = []
        """ LCM Type: double[num_joints] """

    def encode(self):
        buf = BytesIO()
        buf.write(pnd_robot_state_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.num_joints))
        buf.write(struct.pack('>%dd' % self.num_joints, *self.apos[:self.num_joints]))
        buf.write(struct.pack('>%dd' % self.num_joints, *self.avel[:self.num_joints]))
        buf.write(struct.pack('>%dd' % self.num_joints, *self.atau[:self.num_joints]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != pnd_robot_state_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return pnd_robot_state_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = pnd_robot_state_t()
        self.num_joints = struct.unpack(">i", buf.read(4))[0]
        self.apos = struct.unpack('>%dd' % self.num_joints, buf.read(self.num_joints * 8))
        self.avel = struct.unpack('>%dd' % self.num_joints, buf.read(self.num_joints * 8))
        self.atau = struct.unpack('>%dd' % self.num_joints, buf.read(self.num_joints * 8))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if pnd_robot_state_t in parents: return 0
        tmphash = (0xf43346ea6622e44a) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if pnd_robot_state_t._packed_fingerprint is None:
            pnd_robot_state_t._packed_fingerprint = struct.pack(">Q", pnd_robot_state_t._get_hash_recursive([]))
        return pnd_robot_state_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", pnd_robot_state_t._get_packed_fingerprint())[0]

