"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class pnd_imu_t(object):

    __slots__ = ["yaw", "pitch", "roll", "angular_velocity", "linear_acceleration"]

    __typenames__ = ["double", "double", "double", "double", "double"]

    __dimensions__ = [None, None, None, [3], [3]]

    def __init__(self):
        self.yaw = 0.0
        """ LCM Type: double """
        self.pitch = 0.0
        """ LCM Type: double """
        self.roll = 0.0
        """ LCM Type: double """
        self.angular_velocity = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: double[3] """
        self.linear_acceleration = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: double[3] """

    def encode(self):
        buf = BytesIO()
        buf.write(pnd_imu_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ddd", self.yaw, self.pitch, self.roll))
        buf.write(struct.pack('>3d', *self.angular_velocity[:3]))
        buf.write(struct.pack('>3d', *self.linear_acceleration[:3]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != pnd_imu_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return pnd_imu_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = pnd_imu_t()
        self.yaw, self.pitch, self.roll = struct.unpack(">ddd", buf.read(24))
        self.angular_velocity = struct.unpack('>3d', buf.read(24))
        self.linear_acceleration = struct.unpack('>3d', buf.read(24))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if pnd_imu_t in parents: return 0
        tmphash = (0x3b7ffd68c7cba26) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if pnd_imu_t._packed_fingerprint is None:
            pnd_imu_t._packed_fingerprint = struct.pack(">Q", pnd_imu_t._get_hash_recursive([]))
        return pnd_imu_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", pnd_imu_t._get_packed_fingerprint())[0]

